### ISSUE TITLE
 Could not load assembly 'Portable.DataAnnotations

### ISSUE THREAD

**Issue by BlueFire-LLC** [jstedfast/EmailValidation#12]
I get the following error after updating (and installing new) 1.0.1 in both Android and iOS projects.

Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Portable.DataAnnotations, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Portable.DataAnnotations.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(

**Comment by feinstein** [comment]
@jstedfast I had to use `Portable.DataAnnotations` for the validation logic since PCL projects don't have the validation code. I believe you might have forgotten to add them as a dependency on the new Nuget package?

**Comment by jstedfast** [comment]
Thanks. Fixed.
